Add setup from server
SoPra-Team-10/KI pull request #1
Opened 2019-05-29 15:23 UTC by aul12

@jonas-merkle willst du im travis noch den token für sq und slack hinterlegen?

2019-05-29 15:37 UTC, aul12 commented
Bitte erst mergen wenn @jonas-merkle tokens hinzugefügt hat

2019-06-03 10:36 UTC, jonas-merkle requested changes

2019-06-03 10:36 UTC, jonas-merkle commented on .travis.yml
> +    - GH_REPO_NAME: Server
```suggestion
    - GH_REPO_NAME: KI
```

2019-06-03 10:36 UTC, jonas-merkle commented on src/Util/Logging.hpp
> +#ifndef SERVER_LOGGING_HPP
```suggestion
#ifndef KI_LOGGING_HPP
```

2019-06-03 10:36 UTC, jonas-merkle commented on src/Util/Timer.h
> +#ifndef SERVER_TIMER_H
```suggestion
#ifndef KI_TIMER_H
```

2019-06-03 10:57 UTC, Timmifixedit approved these changes
Ist der PR nicht obsolet? Der #2 hat doch schon alles, oder?

2019-06-03 10:59 UTC, jonas-merkle approved these changes

2019-06-03 11:42 UTC, pmo73 approved these changes

2019-06-03 13:10 UTC, aul12 commented
@Timmifixedit ja, der #2 hat alles, ich würde nur ungern alles auf einmal mergen

2019-06-03 13:10 UTC, merged