Eval
SoPra-Team-10/KI pull request #12
Opened 2019-06-18 14:52 UTC by TarikEnderes

2019-06-18 14:56 UTC, aul12 commented
Dir ist bewusst, dass du da noch Konflikte hast?

2019-06-18 15:21 UTC, aul12 requested changes
Noch mal kurz zusammengefasst:
 * Lieber for-each (`for (const auto &item : collection)`), statt indizierte `for`s mit magic values (vor allem für sicherheit und lesbarkeit)
 * `If`s immer in zwei Zeilen und mit {}
 * Auch `shared_ptr` profitieren von referenzen
 * const-correctness auch in `shared_ptr`
 * Wenn return-wert von funktion in variable geschrieben werden soll erfüllt die Type-deduction ihren Job gut ('`auto a = f();` statt `int/double/... a = f()`)
 * Für kleine Hilfsvariablen (bei dir z.B. `team1`) die nur typen ersparen sollen sind `const` referenzen ideal, da kein Overhead, sonst Kopie

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        std::array<std::shared_ptr<gameModel::Bludger>, 2> bludgers = env->bludgers;
```suggestion
        const auto &bludgers = env->bludgers;
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        std::shared_ptr<gameModel::Team> team1 = env->team1;
```suggestion
        const auto &team1 = env->team1;
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        std::shared_ptr<gameModel::Team> team2 = env->team2;
```suggestion
        const auto &team2 = env->team2;
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        for (int i = 0; i < 2; i++) {
```suggestion
        for (const auto &bludger : bludgers) {
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                                   env);
Das kann auch in eine Zeile

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        double valTeam2 = evalTeam(env->team2,
Ebenfalls

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        double valTeam1 = evalTeam(env->team1,
```suggestion
        auto valTeam1 = evalTeam(env->team1,
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        double valTeam2 = evalTeam(env->team2,
```suggestion
        auto valTeam2 = evalTeam(env->team2,
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        double valBludgers = evalBludgers(env);
```suggestion
        auto valBludgers = evalBludgers(env);
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        for(int i = 0; i < 7; i++){
```suggestion
        for(const auto &player : env->team1->getAllPlayers()){
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            if(env->team1->getAllPlayers()[i]->isFined) bannedTeam1++;
Bitte in eine separate Zeile, mit {}

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            if(env->team2->getAllPlayers()[i]->isFined) bannedTeam2++;
Ebenfalls

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        if (seeker->isFined) return val;
Bitte in zwei Zeilen

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            val = 1000 / gameController::getDistance(seeker->position, env->snitch->position) + 1;
Sicher, dass du hier nicht Klammern möchtest? (Punkt vor Strich uns so, sonst kannst du durch 0 teilen)

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +    double evalKeeper(const std::shared_ptr<gameModel::Keeper> keeper,
```suggestion
    double evalKeeper(const std::shared_ptr<gameModel::Keeper> &keeper,
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                      const std::shared_ptr<gameModel::Environment> env) {
```suggestion
                      const std::shared_ptr<gameModel::Environment> &env) {
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        if (keeper->isFined) return val;
Siehe oben

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                if (scoreDiff > -40) val += 20;
S.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                if (scoreDiff >= 40) val += 500;
s.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +
Was soll hier hin?

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +    double evalChaser(const std::shared_ptr<gameModel::Chaser> chaser,
```suggestion
    double evalChaser(const std::shared_ptr<gameModel::Chaser> &chaser,
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                      const std::shared_ptr<gameModel::Environment> env) {
```suggestion
                      const std::shared_ptr<gameModel::Environment> &env) {
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        if (chaser->isFined) return val;
s.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +    double evalBludgers(const std::shared_ptr<gameModel::Environment> env) {
```suggestion
    double evalBludgers(const std::shared_ptr<const gameModel::Environment> &env) {
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            if (team1->keeper->position != bPos) val -= 10 /
s.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                                                         1);
Das kann auch in eine Zeile

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            if (team1->seeker->position != bPos) val -= 20 /
s.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                                                         1);
Das kann auch in eine Zeile

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                if (team1->chasers[j]->position != bPos) val -= 10 / (gameController::getDistance(bPos,
s.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                                                                      1);
kann auch in eine Zeile

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            for (int j = 0; j < 3; j++) {
```suggestion
            for (const auto &chaser : team1->chasers) {
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            for (int j = 0; j < 2; j++) {
```suggestion
            for (const auto &beater : team1->beaters) {
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                if (team1->beaters[j]->position != bPos) val += 20 / (gameController::getDistance(bPos,
s.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                                                                      1);
das kann auch in eine Zeile

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            if (team2->keeper->position != bPos) val += 10 /
s.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            if (team2->seeker->position != bPos) val += 20 /
s.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            for (int j = 0; j < 3; j++) {
```suggestion
            for (const auto &chaser: team2->chasers) {
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                                                                      1);
Eine Zeile

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +            for (int j = 0; j < 2; j++) {
```suggestion
            for (const auto &beater : team2->beaters) {
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                if (team2->beaters[j]->position != bPos) val -= 20 / (gameController::getDistance(bPos,
s.o.

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +                                                                      1);
eine zeile

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +        for (int i = 0; i < 3; i++) {
```suggestion
        for (const auto &goal : goalPos) {
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +    double evalState(const std::shared_ptr<gameModel::Environment> environment, bool isLeft);
```suggestion
    double evalState(const std::shared_ptr<const gameModel::Environment> &environment, bool isLeft);
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +    double evalTeam(const std::shared_ptr<gameModel::Team> team,
```suggestion
    double evalTeam(const std::shared_ptr<const gameModel::Team> &team,
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +                    const std::shared_ptr<gameModel::Environment> env);
```suggestion
                    const std::shared_ptr<const gameModel::Environment> &env);
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +    double evalSeeker(const std::shared_ptr<gameModel::Seeker> seeker,
```suggestion
    double evalSeeker(const std::shared_ptr<const gameModel::Seeker> &seeker,
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +                      const std::shared_ptr<gameModel::Environment> env);
```suggestion
                      const std::shared_ptr<const gameModel::Environment> &env);
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +    double evalKeeper(const std::shared_ptr<gameModel::Keeper> keeper,
```suggestion
    double evalKeeper(const std::shared_ptr<const gameModel::Keeper> &keeper,
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +                      const std::shared_ptr<gameModel::Environment> env);
```suggestion
                      const std::shared_ptr<const gameModel::Environment> &env);
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +    double evalChaser(const std::shared_ptr<gameModel::Chaser> chaser,
```suggestion
    double evalChaser(const std::shared_ptr<const gameModel::Chaser> &chaser,
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +                      const std::shared_ptr<gameModel::Environment> env);
```suggestion
                      const std::shared_ptr<const gameModel::Environment> &env);
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +    double evalBludgers(const std::shared_ptr<gameModel::Environment> env);
```suggestion
    double evalBludgers(const std::shared_ptr<const gameModel::Environment> &env);
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.h
> +    double getHighestGoalRate(std::shared_ptr<gameModel::Environment> env, std::shared_ptr<gameModel::Player> actor);
```suggestion
    double getHighestGoalRate(const std::shared_ptr<const gameModel::Environment> &env, const std::shared_ptr<const gameModel::Player> &actor);
```

2019-06-18 15:21 UTC, aul12 commented on src/Game/AI.cpp
> +    double evalState(const std::shared_ptr<gameModel::Environment> env, bool isLeft, bool goalScoredThisRound) {
```suggestion
    double evalState(const std::shared_ptr<const gameModel::Environment> &env, bool isLeft, bool goalScoredThisRound) {
```

2019-06-18 15:22 UTC, Timmifixedit reviewed
Erstens keine einzeilligen ifs.
Zweitens: const, wo s nur geht. Das gibt dir und anderen Sicherheit, dass man nicht ausversehen was verändert
Drittens: Die Hardcode Werte bitte irgendwo als Konstante definieren
Viertens: Foreaches

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +    double evalState(const std::shared_ptr<gameModel::Environment> env, bool isLeft, bool goalScoredThisRound) {
der shared_ptr sollte vom typ const gameModel::Environment sein. Damit stellst du sicher, dass du das übergebene env nicht veränderst
```suggestion
    double evalState(const std::shared_ptr<const gameModel::Environment> &env, bool isLeft, bool goalScoredThisRound) {
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +            if(env->team1->getAllPlayers()[i]->isFined) bannedTeam1++;
Das Team hat eine Funktion numberOfBannedMembers()

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +            val -= 2000;
Diese ganzen hardcode Werte besser irgendwo als Konstante definieren

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +    double evalTeam(const std::shared_ptr<gameModel::Team> team,
```suggestion
    double evalTeam(const std::shared_ptr<const gameModel::Team> &team, const std::shared_ptr<const gameModel::Environment> &env
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +    double evalSeeker(const std::shared_ptr<gameModel::Seeker> seeker,
```suggestion
    double evalSeeker(const std::shared_ptr<const gameModel::Seeker> &seeker,
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +                      const std::shared_ptr<gameModel::Environment> env) {
```suggestion
                      const std::shared_ptr<const gameModel::Environment> &env) {
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +    double evalKeeper(const std::shared_ptr<gameModel::Keeper> keeper,
```suggestion
    double evalKeeper(const std::shared_ptr<const gameModel::Keeper> &keeper,
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +                      const std::shared_ptr<gameModel::Environment> env) {
```suggestion
                      const std::shared_ptr<const gameModel::Environment> &env) {
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        if (seeker->isFined) return val;
Bitte keine einzeiligen if, das fliegt dir irgendwann um die Ohren. Außerdem kannst du früher returnen und musst die scoreDiff nicht erst berechnen

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        if (keeper->isFined) return val;
siehe oben

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +    double evalChaser(const std::shared_ptr<gameModel::Chaser> chaser,
```suggestion
    double evalChaser(const std::shared_ptr<const gameModel::Chaser> &chaser,
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +                      const std::shared_ptr<gameModel::Environment> env) {
```suggestion
                      const std::shared_ptr<const gameModel::Environment> &env) {
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        if (chaser->isFined) return val;
einzeiliges if..

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +    double evalBludgers(const std::shared_ptr<gameModel::Environment> env) {
```suggestion
    double evalBludgers(const std::shared_ptr<const gameModel::Environment> &env) {
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        std::array<std::shared_ptr<gameModel::Bludger>, 2> bludgers = env->bludgers;
arbeite doch direkt auf dem env. Wenn du sicherstellen willst, dass die Bludger usw nicht verändert werden, dann leg dir ne lokale Copie an mit
```suggestion
        std::array<const std::shared_ptr<const gameModel::Bludger>, 2> &bludgers = env->bludgers;
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        std::shared_ptr<gameModel::Team> team1 = env->team1;
hier auch

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        for (int i = 0; i < 2; i++) {
foreach schleife?
```suggestion
        for (const auto &bludger : bludgers) {
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +            if (team1->keeper->position != bPos) val -= 10 /
SCHMERZ!! Keine einzeiligen ifs

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +            for (int j = 0; j < 3; j++) {
foreach

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +    double getHighestGoalRate(std::shared_ptr<gameModel::Environment> env, std::shared_ptr<gameModel::Player> actor) {
```suggestion
    double getHighestGoalRate(const std::shared_ptr<const gameModel::Environment> &env, const std::shared_ptr<const gameModel::Player> &actor) {
```

2019-06-18 15:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        for (int i = 0; i < 3; i++) {
foreach
```suggestion
        for (const auto &pos : env->getGoalsLeft()) {
```

2019-06-18 18:04 UTC, jonas-merkle requested changes
ich schließe mich da meinen Vorrednern an & würde mich im allgemeinen noch über ein paar Doxygen Kommentare zu den Funktionen in der cpp freuen

2019-06-18 18:04 UTC, jonas-merkle commented on src/Game/AI.cpp
> +            val -= 2000;
und bitte nicht als define sonder am besten als const expression

2019-06-19 11:51 UTC, aul12 approved these changes

2019-06-19 11:51 UTC, aul12 commented
@TarikEnderes  die Doxygen Kommentare für deine Funktionen wären trotzdem noch schön

2019-06-21 05:48 UTC, jonas-merkle approved these changes

2019-06-21 05:51 UTC, jonas-merkle requested changes
Bitte noch den Fehler beim compilieren fixen. (Siehe Travis CI)

2019-06-21 09:22 UTC, aul12 requested changes
Der eine Test ist nicht ordentlich eingerückt. Und ein Test mit nicht symetrischen env wäre noch nett

2019-06-21 09:29 UTC, TarikEnderes commented
Beide Tests sind mit symmetrischen envs (oder sollten sie zumindest).

2019-06-21 09:30 UTC, TarikEnderes commented
> Bitte noch den Fehler beim compilieren fixen. (Siehe Travis CI)

Die CI läuft doch durch

2019-06-21 14:11 UTC, Timmifixedit approved these changes

2019-06-21 14:19 UTC, merged