ComputeAction
SoPra-Team-10/KI pull request #18
Opened 2019-06-22 14:19 UTC by Timmifixedit

2019-06-22 14:58 UTC, aul12 requested changes

2019-06-22 14:58 UTC, aul12 commented on src/Game/AITools.h
> +     * @tparam EvalArgs types of additional arguments passed to evaluation function
Wieso die separat und nicht vom User bereits eine passende Funktion verlangen? Dann muss der User halt `std::bind` selber aufrufen, kann die Reihenfolge der Argumente aber selber anpassen

2019-06-22 14:58 UTC, aul12 commented on src/Game/AITools.h
> +        for(auto action = actionList.begin(); action < actionList.end(); action++){
```suggestion
        for(auto action = actionList.begin(); action < actionList.end(); ++action){
```

2019-06-22 14:58 UTC, aul12 commented on src/Game/AI.h
> +    constexpr auto minShotSuccessProb = 0.2;
muss das im Header sein?

2019-06-22 15:38 UTC, Timmifixedit commented on src/Game/AITools.h
> +     * @tparam EvalArgs types of additional arguments passed to evaluation function
Kann er doch so auch, oder? Ich wollte halt mal variadic templates bauen :/
Aber ich kanns auch auslagern...

2019-06-22 16:32 UTC, aul12 commented on src/Game/AITools.h
> +     * @tparam EvalArgs types of additional arguments passed to evaluation function
Ich seh halt nicht wieso du dann nochmal ein bind aufrufen solltest (also abgesehen von den variadic templates...)

2019-06-22 16:34 UTC, aul12 requested changes

2019-06-22 16:34 UTC, aul12 commented on src/Game/AI.cpp
> +        auto evalFun = [=] (const std::shared_ptr<const gameModel::Environment> &e){
Hier brauchst du ja nicht alles capturen

2019-06-22 16:34 UTC, aul12 commented on src/Game/AI.cpp
> +        auto evalFun = [=] (const std::shared_ptr<const gameModel::Environment> &e){
Auch

2019-06-23 11:51 UTC, TarikEnderes approved these changes

2019-06-23 13:46 UTC, aul12 approved these changes

2019-06-23 13:46 UTC, merged