Improve evaluation
SoPra-Team-10/KI pull request #20
Opened 2019-06-24 09:39 UTC by TarikEnderes

2019-06-24 10:00 UTC, Timmifixedit requested changes

2019-06-24 10:00 UTC, Timmifixedit commented on Tests/AI.cpp
> +    EXPECT_EQ(res, true);
Nutz doch das EXPECT_TRUE / EXPECT_FALSE
```suggestion
    EXPECT_TRUE(res);
```

2019-06-24 10:00 UTC, Timmifixedit commented on Tests/AI.cpp
> +    EXPECT_EQ(res, false);
Siehe oben

2019-06-24 10:00 UTC, Timmifixedit commented on Tests/AI.cpp
> +    EXPECT_EQ(res, true);
Siehe oben

2019-06-24 10:00 UTC, Timmifixedit commented on Tests/AI.cpp
> +    EXPECT_EQ(res, false);
Siehe oben

2019-06-24 10:00 UTC, Timmifixedit commented on Tests/AI.cpp
> +    EXPECT_EQ(chance, env->config.gameDynamicsProbs.throwSuccess);
Hier besser EXPECT_DOUBLE_EQ nutzen, da das ja doubles sind

2019-06-24 10:02 UTC, Timmifixedit requested changes

2019-06-24 10:02 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        std::shared_ptr<gameModel::Team> team = env->team1;
getTeam
```suggestion
        auto team = env->getTeam(player);
```

2019-06-24 10:02 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        for(const auto chaser:team->chasers){
```suggestion
        for(const auto chaser : team->chasers){
```

2019-06-24 10:39 UTC, jonas-merkle commented on src/Game/AI.cpp
> +        constexpr auto keeperBonusPotentialHighWinChance = 200;
die Konstanten könnte man noch groß schreien

2019-06-24 10:40 UTC, jonas-merkle commented on src/Game/AI.cpp
> +        std::shared_ptr<gameModel::Team> team = env->team1;
kommt man nicht auch evtl ohne die team hilfsvariable aus?

2019-06-24 10:51 UTC, aul12 requested changes

2019-06-24 10:51 UTC, aul12 commented on Tests/AI.cpp
> +    EXPECT_EQ(val, 0);
Ich nehme an `val` ist ein `double`, dann `EXPECT_DOUBLE_EQ`

2019-06-24 15:44 UTC, pmo73 commented on src/Game/AI.cpp
> +        std::shared_ptr<gameModel::Team> team = env->team1;
man könnte ja auch sich zuerst über die Position vom Ball schauen ob überhaupt ein Spieler drauf steht...
```suggestion
        auto optionalPlayer = env->getPlayer(env->quaffle->position);
        if(optionalPlayer.has_value()){
        if(env->getTeam(optionalPlayer)->side == env->getTeam(player)){
        return true;
        }
        }
```

2019-06-24 15:45 UTC, pmo73 commented on src/Game/AI.cpp
> +        std::shared_ptr<gameModel::Team> team = env->team1;
ist die Frage ob es so viel schöner wird?

2019-06-24 15:46 UTC, pmo73 commented on src/Game/AI.h
> +    bool teamHasQuaffle(const std::shared_ptr<const gameModel::Environment> &env, const std::shared_ptr<gameModel::Player> &player);
```suggestion
    bool teamHasQuaffle(const std::shared_ptr<const gameModel::Environment> &env, const std::shared_ptr<const gameModel::Player> &player);
```

2019-06-24 15:47 UTC, pmo73 requested changes
Vielleicht geht es so schöner in der TeamHasQuaffle

2019-06-25 09:31 UTC, TarikEnderes commented on src/Game/AI.cpp
> +        std::shared_ptr<gameModel::Team> team = env->team1;
getTeam scheint mit optional Player nicht zu funktionieren

2019-06-25 09:38 UTC, aul12 commented on src/Game/AI.cpp
> +        std::shared_ptr<gameModel::Team> team = env->team1;
Ja, das muss dann ja auch `env->getTeam(optionalPlayer.value())->side` sein

2019-06-25 22:44 UTC, pmo73 approved these changes

2019-06-27 08:29 UTC, jonas-merkle requested changes

2019-06-27 08:29 UTC, jonas-merkle commented on Tests/AI.cpp
> +    auto valLeft = ai::evalState(env, gameModel::TeamSide::LEFT, false, <#initializer#>);
`<#initializer#>` ist bisschen schieße wenn des noch drin ist

2019-06-27 08:29 UTC, jonas-merkle commented on Tests/AI.cpp
> +    auto valRight = ai::evalState(env, gameModel::TeamSide::RIGHT, false, <#initializer#>);
`<#initializer#>` ist bisschen schieße wenn des noch drin ist

2019-06-27 08:29 UTC, jonas-merkle commented on Tests/AI.cpp
> +    auto valLeft = ai::evalState(env, gameModel::TeamSide::LEFT, false, <#initializer#>);
`<#initializer#>` ist bisschen schieße wenn des noch drin ist

2019-06-27 08:29 UTC, jonas-merkle commented on Tests/AI.cpp
> +    auto val = ai::evalState(env, gameModel::TeamSide::LEFT, false, <#initializer#>);
`<#initializer#>` ist bisschen schieße wenn des noch drin ist

2019-06-27 08:29 UTC, jonas-merkle commented on Tests/AI.cpp
> +    auto res = ai::computeBestMove(env, playerId, false, <#initializer#>);
`<#initializer#>` ist bisschen schieße wenn des noch drin ist

2019-06-27 08:29 UTC, jonas-merkle commented on Tests/AI.cpp
> +    auto res = ai::computeBestShot(env, playerId, false, <#initializer#>);
`<#initializer#>` ist bisschen schieße wenn des noch drin ist

2019-06-27 08:29 UTC, jonas-merkle commented on Tests/AI.cpp
> +    auto res = ai::computeBestShot(env, playerId, false, <#initializer#>);
`<#initializer#>` ist bisschen schieße wenn des noch drin ist

2019-06-27 08:29 UTC, jonas-merkle commented on Tests/AI.cpp
> +    auto res = ai::computeBestWrest(env, playerId, false, <#initializer#>);
`<#initializer#>` ist bisschen schieße wenn des noch drin ist

2019-06-27 08:29 UTC, jonas-merkle commented on Tests/AI.cpp
> +    auto res = ai::redeployPlayer(env, env->getPlayerById(id)->id, <#initializer#>);
`<#initializer#>` ist bisschen schieße wenn des noch drin ist

2019-06-30 15:26 UTC, aul12 commented
Wo sind denn die Tests hin?

2019-07-01 17:55 UTC, jonas-merkle commented
Es gibt leider immernoch / schon wieder Merge-Konflikte

2019-07-06 09:17 UTC, TarikEnderes commented
Nicht vergessen zu reviewn

2019-07-07 16:49 UTC, TarikEnderes commented
> Wo sind denn die Tests hin?

Die meisten sind jetzt bei den AITools. Vier sind beim Umbau verschwunden, aber die Funktion die die getestet haben funktioniert und wird auch nicht mehr verändert.

2019-07-07 19:01 UTC, aul12 commented
>  Vier sind beim Umbau verschwunden, aber die Funktion die die getestet haben funktioniert und wird auch nicht mehr verändert.

Really?!

2019-07-08 19:09 UTC, Timmifixedit approved these changes

2019-07-08 19:26 UTC, aul12 commented
Die Tests wirst du doch hoffentlich wiederfinden

2019-07-09 08:34 UTC, aul12 approved these changes

2019-07-09 10:49 UTC, merged