Get next fan turn
SoPra-Team-10/KI pull request #22
Opened 2019-06-24 13:38 UTC by pmo73

2019-06-24 14:06 UTC, Timmifixedit requested changes

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +    communication::messages::broadcast::Next next = communication::messages::broadcast::Next{communication::messages::types::EntityId::LEFT_GOBLIN, communication::messages::types::TurnType::FAN, 30};
Einfach direkt den Ctor aufrufen
```suggestion
    communication::messages::broadcast::Next next{communication::messages::types::EntityId::LEFT_GOBLIN, communication::messages::types::TurnType::FAN, 30};
```

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +        std::optional<communication::messages::types::EntityId> entityId = deltaRequest.getPassiveEntity();
Auto hilft
```suggestion
        auto entityId = deltaRequest.getPassiveEntity();
```

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +            throw std::runtime_error("No Passive EntityID");
Hier keine Exception werfen, sondern einfach den Test failen lassen. Is j offensichtliches Fehlverhalten...

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +            EXPECT_TRUE(env->getTeam(player)->side == gameModel::TeamSide::RIGHT);
Das macht die RangedAttack::isPossible() schon. Das musst und soltest du nicht abprüfen

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +    communication::messages::broadcast::Next next = communication::messages::broadcast::Next{communication::messages::types::EntityId::LEFT_WOMBAT, communication::messages::types::TurnType::FAN, 30};
Siehe Anmerkungen oben.

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +    auto env = setup::createEnv();
Du könntest hier lokal den Namespace usen. Dann werden die Typen nicht so lang

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +    EXPECT_EQ(deltaRequest.getDeltaType(), communication::messages::types::DeltaType::SKIP);
Es könnte auch ein Wombat-Turn rauskommen. Falls ja muss auch geprüft werden, ob der Turn valide ist

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +TEST(ai_test, getNextFanTurn2){
Siehe vorherige Anmerkungen

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +        std::optional<communication::messages::types::EntityId> entityId = deltaRequest.getPassiveEntity();
Bei Trollen ist glaube ich keine passive Entity gesetzt

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +TEST(ai_test, getNextFanTurn3){
Siehe stuff von vorher

2019-06-24 14:06 UTC, Timmifixedit commented on Tests/AI.cpp
> +        std::optional<communication::messages::types::EntityId> entityId = deltaRequest.getPassiveEntity();
Keine passive Entity

2019-06-24 14:06 UTC, Timmifixedit commented on src/Game/AI.cpp
> +    auto getDistance(const gameModel::Position &startPoint, const gameModel::Position &endPoint) -> int {
raus damit

2019-06-24 14:06 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        communication::messages::types::EntityId activeEntityId = next.getEntityId();
namespace

2019-06-24 14:06 UTC, Timmifixedit commented on src/Game/AI.cpp
> +            passiveEntityId = isElfUseful(mySide, env, excessLength);
bitte Rename, Name suggeriert bool

2019-06-24 14:06 UTC, Timmifixedit commented on src/Game/AI.cpp
> +            return getDistance(env->team2->seeker->position, env->snitch->position) <= 2;
Hardcode-Werte bitt irgendwo als Konstante

2019-06-24 14:06 UTC, Timmifixedit commented on src/Game/AI.cpp
> +        if (mySide == env->team1->side) {
Hol dir einfach den Spieler auf der Position des Balls. Wenn da einer drauf steht, prüfe, ob er in deinem Team ist.

2019-06-24 14:06 UTC, Timmifixedit commented on src/Game/AI.cpp
> +                        const std::shared_ptr<gameModel::Environment> &env) -> const std::optional<communication::messages::types::EntityId> {
const 
```suggestion
                        const std::shared_ptr<const gameModel::Environment> &env) -> const std::optional<communication::messages::types::EntityId> {
```

2019-06-24 14:06 UTC, Timmifixedit commented on src/Game/AI.cpp
> +    auto isElfUseful(const gameModel::TeamSide &mySide, const std::shared_ptr<gameModel::Environment> &env,
const 
```suggestion
    auto isElfUseful(const gameModel::TeamSide &mySide, const std::shared_ptr<const gameModel::Environment> &env,
```

2019-06-24 14:06 UTC, Timmifixedit commented on src/Game/AI.cpp
> +            if (getDistance(environment->team2->seeker->position, environment->snitch->position) <= 2) {
Hardcode

2019-06-24 16:05 UTC, aul12 requested changes

2019-06-24 16:05 UTC, aul12 commented on Tests/AI.cpp
> +#define testTimeout 30
bitte als `constexpr`, nicht als define

2019-06-24 16:05 UTC, aul12 commented on Tests/AI.cpp
> +    communication::messages::broadcast::Next next {communication::messages::types::EntityId::LEFT_GOBLIN, communication::messages::types::TurnType::FAN, testTimeout};
```suggestion
    communication::messages::broadcast::Next next{communication::messages::types::EntityId::LEFT_GOBLIN, communication::messages::types::TurnType::FAN, testTimeout};
```

2019-06-24 16:05 UTC, aul12 commented on src/Game/AI.cpp
> +        }
Wofür ist das else hier gut?

2019-06-24 16:05 UTC, aul12 commented on src/Game/AI.h
> +    bool isNifflerUseful(const gameModel::TeamSide &mySide, const std::shared_ptr<const gameModel::Environment> &env);
Doku

2019-06-24 16:55 UTC, jonas-merkle requested changes

2019-06-24 16:55 UTC, jonas-merkle commented on src/Game/AI.cpp
> +#define distanceSnitchToSeeker 2
Auch `constexpr`

2019-06-25 08:07 UTC, aul12 requested changes

2019-06-25 08:07 UTC, aul12 commented on Tests/AI.cpp
> +constexpr int testTimeout = 30;
Brauchst du die überhaupt, das kannst du doch auch einfach unten auf Null setzten, oder?

2019-06-25 08:27 UTC, Timmifixedit requested changes

2019-06-25 08:27 UTC, Timmifixedit commented on Tests/AI.cpp
> +constexpr int testTimeout = 30;
Das hab ich auch immer auf 0 gesetzt

2019-06-25 08:27 UTC, Timmifixedit commented on src/Game/AI.cpp
> +constexpr int distanceSnitchSeeker = 2;
bitte in den namespace verschieben

2019-06-25 09:05 UTC, aul12 approved these changes

2019-06-25 09:11 UTC, Timmifixedit approved these changes

2019-06-25 09:11 UTC, merged