Handle pause
SoPra-Team-10/KI pull request #30
Opened 2019-07-05 14:35 UTC by Timmifixedit

2019-07-05 15:09 UTC, jonas-merkle requested changes
Warum faild die CI? Gibt es da wieder irgendwelche fehlerhaften Abhängigkeiten?

2019-07-06 20:01 UTC, aul12 requested changes

2019-07-06 20:01 UTC, aul12 commented on src/Communication/Communicator.cpp
> +            std::this_thread::sleep_for(std::chrono::milliseconds{200});
Wofür ist das gut?

2019-07-06 20:01 UTC, aul12 commented on src/Communication/Communicator.cpp
> +            cv.wait(lock, [this] { return !paused; });
Was wenn keine Pause? Dann hoffst du hier doch auf einen spurious wakeup

2019-07-06 20:01 UTC, aul12 commented on src/Communication/Communicator.hpp
> +        bool paused = false;
Das wird doch aus verschiedenen Threads genutzt, dann atomic, sonst undefiniertes Verhalten

2019-07-06 20:01 UTC, aul12 commented on src/Communication/Communicator.cpp
> +        if(!once){
worker.valid()

2019-07-06 20:01 UTC, aul12 commented on src/Game/Game.cpp
> +    timer.setTimeout([&abort](){ abort = true; }, next.getTimout() - TIMEOUT_TOLERANCE);
Wenn Funktion Fertig, dann Timeout und erst dann Timeout Zugriff auf undefiniert Adresse auf dem Stack

2019-07-07 12:03 UTC, Timmifixedit commented on src/Communication/Communicator.cpp
> +            std::this_thread::sleep_for(std::chrono::milliseconds{200});
Das war zumindst im develop build nötig. Bevor der thread prüft, ob das pause flag gesetzt ist, muss man kurz warten, weil der worker thread vor dem main thread dran kommt und dann das Pause flag zu spät erkannt wird. Im release konnte ich den Fehler nicht reproduzieren, weil die KI da viel zu schnell ist, als dass man während eines Zuges Pause senden könnte

2019-07-07 12:04 UTC, Timmifixedit commented on src/Communication/Communicator.cpp
> +            cv.wait(lock, [this] { return !paused; });
Das funktioniert ohne Probleme. Alternativ könnte man das ganze Ding in eine if wrappen und pause zu einem atomic_bool machen

2019-07-07 12:05 UTC, Timmifixedit commented on src/Communication/Communicator.hpp
> +        bool paused = false;
Das machen die auf der cppreference im Beispiel auch mit einem normalen bool. deswegen hast du ja davor immer den mutex lock

2019-07-07 12:06 UTC, Timmifixedit commented on src/Game/Game.cpp
> +    timer.setTimeout([&abort](){ abort = true; }, next.getTimout() - TIMEOUT_TOLERANCE);
Also den timer vor dem return stoppen?

2019-07-07 12:11 UTC, aul12 commented on src/Communication/Communicator.cpp
> +            std::this_thread::sleep_for(std::chrono::milliseconds{200});
Unabhängig davon was du da tust ist ein delay **nie** der richtige Weg um Raceconditions zu verhindern!

2019-07-07 12:12 UTC, aul12 commented on src/Communication/Communicator.cpp
> +            cv.wait(lock, [this] { return !paused; });
Wie gesagt du hoffst hier auf ein spurious wakeup, der wird dir aber von niemandem garantiert!

2019-07-07 12:12 UTC, aul12 commented on src/Communication/Communicator.hpp
> +        bool paused = false;
Du kannst so aber nicht garantieren dass die einzelnen Threads das nicht cachen

2019-07-07 12:13 UTC, aul12 commented on src/Game/Game.cpp
> +    timer.setTimeout([&abort](){ abort = true; }, next.getTimout() - TIMEOUT_TOLERANCE);
ja

2019-07-09 10:51 UTC, aul12 requested changes

2019-07-09 10:51 UTC, aul12 commented on src/Communication/Communicator.cpp
> +                cvMainToWorker.wait(lock, [this] { return paused ? false : true; });
```suggestion
                cvMainToWorker.wait(lock, [this] { return !paused; });
```

2019-07-09 10:51 UTC, aul12 commented on src/Communication/Communicator.cpp
> +            if((*request).getActiveEntity().has_value()){
```suggestion
            if(request->getActiveEntity().has_value()){
```

2019-07-09 10:51 UTC, aul12 commented on src/Communication/Communicator.cpp
> +            log.debug("Type sent: " + communication::messages::types::toString((*request).getDeltaType()));
```suggestion
            log.debug("Type sent: " + communication::messages::types::toString(request->getDeltaType()));
```

2019-07-09 10:51 UTC, aul12 commented on src/Communication/Communicator.cpp
> +                log.debug("ID sent: " + communication::messages::types::toString((*request).getActiveEntity().value()));
```suggestion
                log.debug("ID sent: " + communication::messages::types::toString(request->getActiveEntity().value()));
```

2019-07-09 10:51 UTC, aul12 commented on src/Game/Game.cpp
> +            timer.stop();
Rausziehen

2019-07-09 11:16 UTC, aul12 approved these changes

2019-07-09 11:16 UTC, merged