Best path search
SoPra-Team-10/KI pull request #8
Opened 2019-06-16 17:10 UTC by Timmifixedit

Hier die gewünschte Funktion, um optimal mit einem Spieler zu einer Position zu ziehen, ohne Fouls zu begehen. @aul12 schau auch bitte genau auf z.B. unnötige oder vermeidbare copies o.Ä. Hier gehts nämlich wirklich um Geschwindigkeit

2019-06-16 17:44 UTC, TarikEnderes approved these changes
Hat es einen bestimmten Grund, dass die Funktion in der AI.cpp und nicht in der AITools.cpp definiert ist?

2019-06-16 18:15 UTC, Timmifixedit commented
@TarikEnderes Das muss man leider so machen, weil das template Funktionen / Klassen sind

2019-06-16 18:21 UTC, Timmifixedit commented
Ach, Quatsch. Ich hätte deine Frage lesen sollen. Ich dachte mir, in der AI werden Funktionen definiert, die nacher direkt aus dem Game gecallt werden. Und die Toolbox ist für allerlei Hilfsfunktionen, wie z.B. Suchalgorithmen, oder andere Otimierer...

2019-06-17 06:02 UTC, jonas-merkle commented on Tests/setup.h
> +//
Des ist jetzt halt etwas redundant mit dem was im GameModel schon ist... Aber das jetzt auslagern ist beinahe den Aufwand ned Wert

2019-06-17 06:23 UTC, jonas-merkle requested changes

2019-06-17 06:23 UTC, jonas-merkle commented on src/Game/AITools.h
> +    auto aStarSearch(SearchNode<T> &start, SearchNode<T> &destination,
Könnte man des nicht in die cpp Auslagern so wie wir das auch mit den template Klassen im Game Model hatten? Also über Explicit instantiation von dem Zeug in der cpp

2019-06-17 06:23 UTC, jonas-merkle commented on src/Game/AITools.h
> +    bool SearchNode<T>::operator==(const SearchNode<T> &other) const {
Auslagern?

2019-06-17 08:21 UTC, aul12 requested changes

2019-06-17 08:21 UTC, aul12 commented on Tests/AI.cpp
> +    EXPECT_EQ(path.front(), gameModel::Position(8, 6));
Hier vielleicht noch `path.back` überprüfen, sonst kann der ja ins nirgendwo gehen

2019-06-17 08:21 UTC, aul12 commented on Tests/AI.cpp
> +    EXPECT_EQ(path.front(), gameModel::Position(0, 4));
Ebenfalls

2019-06-17 08:21 UTC, aul12 commented on Tests/AI.cpp
> +    EXPECT_EQ(path.front(), gameModel::Position(15, 9));
Auch

2019-06-17 08:21 UTC, aul12 commented on Tests/AI.cpp
> +    EXPECT_EQ(path.front(), gameModel::Position(9, 4));
Auch

2019-06-17 08:21 UTC, aul12 commented on src/Game/AI.cpp
> +            int g = pos.parent.has_value() ? pos.parent.value()->pathCost + 1: 1;
optional hat ein `value_or`

2019-06-17 08:21 UTC, aul12 commented on src/Game/AI.cpp
> +        auto res = aiTools::aStarSearch<gameModel::Position>(startNode, destinationNode, expandFunction, evalFunction);
Bennenung, eine Variable `res` und eine `ret` zu nennen hilft nicht wirklich

2019-06-17 08:21 UTC, aul12 commented on src/Game/AITools.cpp
> +//
Kommt in das File noch was rein?

2019-06-17 08:21 UTC, aul12 commented on src/Game/AITools.h
> +        T state;
Muss das Public sein? Vielleicht als friend class wenn benötigt?

2019-06-17 08:21 UTC, aul12 commented on src/Game/AITools.h
> +        SearchNode(T state, std::optional<std::shared_ptr<SearchNode<T>>> parent, int pathCost) :
Wo ist denn hier die implementierung?

2019-06-17 08:21 UTC, aul12 commented on src/Game/AITools.h
> +            std::function<std::vector<SearchNode<T>>(const SearchNode<T>&)> expand,
Als referenz?

2019-06-17 08:21 UTC, aul12 commented on src/Game/AITools.h
> +        std::optional<SearchNode<T>> ret = std::nullopt;
Default konstruktion wird auch schon mit `nullopt` gemacht

2019-06-17 08:21 UTC, aul12 commented on src/Game/AITools.h
> +                for(auto it = fringe.begin(); it != fringe.end(); it++){
```suggestion
                for(auto it = fringe.begin(); it != fringe.end(); ++it){
```
Ist allgemein in jeder for-Schleife theoretisch performanter das als pre-increment (statt post) zu machen (`add` + wert zurückgeben vs. kopie vom alten Wert machen und dann `add`). Bei trivialen typen wie `int` wird der compiler das optimieren, bei nicht trivialen typen mit überladenen Operatoren geht das nicht, da nicht garantiert werden kann, dass `++it` und `it++` das gleiche machen

2019-06-17 08:21 UTC, aul12 commented on src/Game/AITools.h
> +            std::function<int(const SearchNode<T>&)> f) -> std::optional<SearchNode<T>>{
Normalerweise werden funktionen die functoren akzeptieren getemplated. Da `std::function` nur ein Container für alles aufrufbare ist, wenn da direkt der richtige typ übergeben werden kann ist das performanter.

2019-06-17 11:22 UTC, Timmifixedit commented on src/Game/AI.cpp
> +            int g = pos.parent.has_value() ? pos.parent.value()->pathCost + 1: 1;
Da müsste ich aber im value_or() eine neue SearchNode instanziieren... Ist das nicht performanter, wenn ich das so mache?

2019-06-17 11:24 UTC, Timmifixedit commented on src/Game/AITools.cpp
> +//
Im Moment sind halt alle Funktionen / Klassen templatisiert, aber da kommen vllt in Zukunft noch Sachen rein

2019-06-17 11:25 UTC, Timmifixedit commented on src/Game/AITools.h
> +        T state;
Soll ichs private machen und nen getter dafür schreiben, der s als const T& liefert?

2019-06-17 15:35 UTC, aul12 approved these changes

2019-06-17 15:35 UTC, aul12 commented on src/Game/AITools.h
> +        T state;
Oder als friend class

2019-06-17 15:35 UTC, aul12 commented on src/Game/AI.cpp
> +            int g = pos.parent.has_value() ? pos.parent.value()->pathCost + 1: 1;
Stimmt auch

2019-06-18 11:12 UTC, merged